#!/usr/bin/perl

use File::Find;

sub Wanted {
    my $file = $File::Find::name;
    my $dir = $File::Find::dir;
    if ($file =~ /\.(mkv|mpeg|mpg|avi|wmv|mp4|xvid|mov|rmvb|divx)$/i) {
	($dev, $ino, $mode, $nlink, $uid, $gid, $rdev, $size,
	 $atime, $mtime, $ctime, $blksize, $blocks) = stat($file);
	if (-f $file &&
	    $size > 0 &&
	    ! -e "$file.png" &&
	    $mtime + 60 < time()) {
	    chdir "/tmp";
	    print "$file\n";
	    system("ffmpeg", "-i", $file,
		   "-r", "30", "-f", "image2",
		   "-frames:v", "1", "-ss", "20", "image%03d.png");
	    system("convert", "-scale", "300x",
		   "/tmp/image001.png", "$file.png");
	    unlink("/tmp/image001.png");
	}
    }
}

find(\&Wanted, "/tv/");
